# Generated by Django 5.1.3 on 2025-08-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("introducao", models.TextField()),
                ("resumo", models.TextField()),
                ("referencial_teorico", models.TextField()),
                ("desenvolvimento", models.TextField()),
                ("resultados", models.TextField()),
                ("conclusao", models.TextField()),
                ("referencias", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
