# Generated by Django 5.1.3 on 2025-08-19 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipe", "0001_initial"),
        ("projeto", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos_participados",
                through="equipe.Equipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
