# Generated by Django 5.1.3 on 2025-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0003_projeto_membros"),
        ("projetotag", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos",
                through="projetotag.ProjetoTag",
                to="tag.tag",
            ),
        ),
    ]
