# Generated by Django 5.1.3 on 2025-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Critério"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "peso",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Define a importância deste critério no cálculo da nota final.",
                        verbose_name="Peso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
            },
        ),
    ]
