# Generated by Django 5.1.3 on 2025-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="add_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="datanasc",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
