# Generated by Django 5.1.3 on 2025-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_alter_usuario_add_em_alter_usuario_datanasc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aluno", "Aluno"),
                    ("Orientador", "Orientador"),
                    ("Avaliador", "Avaliador"),
                ],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
