# Generated by Django 5.1.3 on 2025-08-19 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Avaliação"
                    ),
                ),
                (
                    "nota_final",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Nota Final"
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Avaliador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
            },
        ),
    ]
