# Generated by Django 5.1.3 on 2025-08-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avaliacao", "0001_initial"),
        ("barema", "0001_initial"),
        ("criterio", "0001_initial"),
        ("projeto", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="criterios",
            field=models.ManyToManyField(
                through="barema.Barema", to="criterio.criterio"
            ),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="projeto.projeto",
                verbose_name="Projeto",
            ),
        ),
    ]
