# Generated by Django 5.1.3 on 2025-08-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projeto", "0003_projeto_membros"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.projeto",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tag.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto Tag",
                "verbose_name_plural": "Projetos Tags",
                "unique_together": {("projeto", "tag")},
            },
        ),
    ]
